In [1]:
# comments

## Numbers
Using numbers in python and math.

In [2]:
# int
1

1

In [3]:
# float
1.0

1.0

In [4]:
# addition
1+1

2

In [5]:
# multiplication
1*3

3

In [6]:
# python 2 division
1/2.0
# python 3
1/2

0.5

In [7]:
# two to the power of 4
2 ** 4

16

In [8]:
# mod function
# if zero then even number
4 % 2

0

In [9]:
# remainder left over is 1
5 % 2

1

In [10]:
5 / 2

2.5

## Variables
Using variables in python.

In [248]:
# without () ouputs like normal math
xx = 4 + 2 * 3 + 6
print (xx)
# with () ouputs like normal math
yy = (4 + 2) * (3 + 6)
print (yy)

16
54


In [249]:
var = 2

In [250]:
# you can output in jupyter like
var

2

In [251]:
# however, print() is the common practice
print(var)

2


In [252]:
x = 2
y = 3

In [253]:
x+y

5

In [254]:
x = x+x

In [255]:
x

4

In [256]:
x = x+x

In [257]:
x

8

In [258]:
# variables can not start with numbers
111var = 5

SyntaxError: invalid syntax (<ipython-input-258-82b7c26456e4>, line 2)

In [259]:
# proper variables use "snake_case"
the_variable_name = 5

## Strings
Strings in python work like...

In [260]:
# string with '' quotes
'single quotes'

'single quotes'

In [261]:
# string with "" quotes
"double quotes"

'double quotes'

In [262]:
# string with a single ' and "" wrapping
"double's quote"

"double's quote"

In [263]:
# string with a single " and '' wrapping
'single"s quote'

'single"s quote'

## Using variables with strings
Strings/numbers and their usage with variables.

In [264]:
# printing
to_print = "hi wrold"

In [265]:
# works in jupyter
to_print

'hi wrold'

In [266]:
# common practice
print(to_print)

hi wrold


In [267]:
# using variable names in format()
num = 15
name = 'Tyler'
title = 'The Beast'
# format(order,you,want,variables_to_pass_in_brace_brackets)
print('My fave # is {} and my name is {}, {}'.format(num,name,title))
# here we can re-use without worrying about order
print('My fave # is {one} and my name is {two}, {three} named {two}-zilla-g'.format(one=num,two=name,three=title))

My fave # is 15 and my name is Tyler, The Beast
My fave # is 15 and my name is Tyler, The Beast named Tyler-zilla-g


In [268]:
s='hello'

In [269]:
# indexing starts at zero
# counting in python starts with zero, then one, two, etc.
s[0]

'h'

In [270]:
# grabbing "o" from hello.
s[4]

'o'

In [271]:
# how it's done using numbers, in a list, a little similar
g=[0,1,2,3]

In [272]:
g[2]

2

## Trimming a string.
Trimming strings in python and examples.

In [273]:
# r is a sequence of elements
r='asfghjkl'
# [number:number] lets you grab a sequence of elements
# column notation, aka 'slice syntax'
# trim 1 letter from the left
r[1:]

'sfghjkl'

In [274]:
# trim 3 letter from the right
r[:3]

'asf'

In [275]:
# adding negative reverses the trim direction
# example; trim 3 letter from the left
r[:-3]

'asfgh'

In [276]:
# trim 3 letter from the left
r[3:]

'ghjkl'

In [277]:
# adding negative reverses the trim starting direction
# example; trim 3 letter from the left
r[-3:]

'jkl'

In [278]:
r[2:5]

'fgh'

## Lists
Using a list in python with examples.

In [279]:
# lists numbers
[1,2,3]

[1, 2, 3]

In [280]:
# lists strings
['a','b','c']

['a', 'b', 'c']

In [281]:
# variable with string list
a_cool_list = ['a','b','c']
# appending 'meow'
a_cool_list.append('meow')
print (a_cool_list)
# removing 'meow'
a_cool_list.remove('meow')
print (a_cool_list)

['a', 'b', 'c', 'meow']
['a', 'b', 'c']


In [282]:
# appending 'd'
a_cool_list.append('d')
# print to check change
print (a_cool_list)
a_cool_list.append('e')
# print to check change
print (a_cool_list)
a_cool_list.append('f')
# print to check change
print (a_cool_list)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e']
['a', 'b', 'c', 'd', 'e', 'f']


In [283]:
# trim both sides of the list
a_cool_list[2:5]

['c', 'd', 'e']

In [284]:
# change the value in the list based on index #\
a_cool_list[0] = 'Meow'
a_cool_list

['Meow', 'b', 'c', 'd', 'e', 'f']

## Tuples vs lists vs sets
Tuples can't be changed, lists can be changed. Use tuple when user can't change what's inside of object.

In [285]:
# tuple ()
t = ('new','car','vroom')
# list []
l = ['new','car','vroom']

# attempting to change first value in tuple
# tuples can not be changed, will fail, see error
# items in tuple can not be mutated
t[0] = 'fast'

TypeError: 'tuple' object does not support item assignment

In [286]:
# change first value to 'fast'
# lists can be changed
l[0] = 'fast'
# print list to see change
print(l)

['fast', 'car', 'vroom']


In [287]:
# sets [], a set only passes unique elements when printed
# sets are a collection of unique elements
# vroom 2 will be removed in s
s = {'new','car','vroom','vroom'} 
# print to see vroom removed
print(s)

{'vroom', 'new', 'car'}


In [288]:
# adding 5 to set
s.add(5)
print(s)

{'vroom', 'new', 'car', 5}


In [289]:
# convert list to set with set()
convert = set([1,1,1,1,1,12,2,3,4,5,5,5,5,5,55,33])
# print to see unique elements.
print(convert)

{1, 2, 3, 4, 5, 33, 12, 55}


##  Dictonary
A dictonary in python. Dictonary do not retain an order, they are key value paired mappings. 

In [290]:
d = {'key1':'value','key2':123}
d['key2']

123

In [291]:
d['key1']

'value'

In [292]:
d={'k1':[1,2,3]}

In [293]:
d

{'k1': [1, 2, 3]}

In [294]:
d['k1']

[1, 2, 3]

In [295]:
print(d['k1'][1])
a_list = d['k1']

2


In [296]:
a_list[1]

2

## Comparison operators
Comparison operators allow you to compare two elements to each other, and booleans.

In [297]:
1 > 3

False

In [298]:
1 < 3

True

In [299]:
1 >= 3

False

In [300]:
1 <= 3

True

In [301]:
1 == 3

False

In [302]:
1 = 1

SyntaxError: cannot assign to literal (<ipython-input-302-ecdac3dcabfd>, line 1)

In [303]:
1 != 3

True

In [304]:
'hi' != 'bye'

True

In [305]:
1 < 2 and 2 < 3

True

In [306]:
1 < 2 and 2 > 3

False

In [307]:
# more readable
(1 < 2) or (2 < 1)

True

In [308]:
# more readable
(1 < 2) and (2 < 1)

False

In [309]:
True and True

True

In [310]:
False or True

True

## If statement
If then else...

In [311]:
if 1<2:
    print('woot!')

woot!


In [312]:
if True:
    print('output code')

output code


In [313]:
# needs to be uppercase first letter
if true:
    print('output code')

NameError: name 'true' is not defined

In [314]:
if 1 == 2:
    print ('tyker')
else:
    print ('garr3ttt')

garr3ttt


In [315]:
# python only executes the first true statement, and that's all.
if 1 == 2:
    print ('tyker')
elif 'meow' == 'meow':
    print ('m3ow')
elif 3 == 3:
    print ('alexand3r')
else:
    print ('garr3ttt')

m3ow


## for loop

In [316]:
seq = [1,2,3,4,5,6,7,8,9]

In [317]:
for i in seq:
    print(i)

1
2
3
4
5
6
7
8
9


In [318]:
for number in seq:
    print(number)

1
2
3
4
5
6
7
8
9


In [319]:
# while loops
# execute a loop, as long as the condition is true.
i = 1
# i < 10 is the condition that needs to be true for the loop to run
while i < 10:
    # printing each loop the following
    print ('You gained ${a}.00 USD'.format(a=i))
    # increases +1 per loop, until it reaches 10<10 which is not true
    i = i+1

You gained $1.00 USD
You gained $2.00 USD
You gained $3.00 USD
You gained $4.00 USD
You gained $5.00 USD
You gained $6.00 USD
You gained $7.00 USD
You gained $8.00 USD
You gained $9.00 USD


In [320]:
i = 1
c = 10
while i < c:
    print ('You gained ${}.00 USD, out of ${}.00 total'.format(i, c))
    i = i+1

You gained $1.00 USD, out of $10.00 total
You gained $2.00 USD, out of $10.00 total
You gained $3.00 USD, out of $10.00 total
You gained $4.00 USD, out of $10.00 total
You gained $5.00 USD, out of $10.00 total
You gained $6.00 USD, out of $10.00 total
You gained $7.00 USD, out of $10.00 total
You gained $8.00 USD, out of $10.00 total
You gained $9.00 USD, out of $10.00 total


## For loop and Range

In [321]:
m = [1,2,3,4,5,5]
for x in m:
    print(x)

1
2
3
4
5
5


In [322]:
# using a list generator, range()
for x in range(0,5):
    print(x)

0
1
2
3
4


In [323]:
# using a list generator, range()
for x in list(range(0,5)):
    print(x)

0
1
2
3
4


In [324]:
list(range(0,6))

[0, 1, 2, 3, 4, 5]

In [325]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [326]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## List comprehension
List comprehension - save writing when you're creating a for loop to create a list

In [327]:
# for loop can be used, however list comprehension below is 1 line
# a list of numbers (num)
h = [1,2,3,4]
# defining a list "out"
out = []

for num in h:
    out.append(num**2)

print(out)

[1, 4, 9, 16]


In [328]:
io = [num**2 for num in h]
print(io)

[1, 4, 9, 16]


In [329]:
[num**2 for num in h]

[1, 4, 9, 16]

## Functions
A function in python helps you write less code.

In [330]:
def my_function(param1):
    print(param1)

In [331]:
my_function('hey world')

hey world


In [332]:
def my_func(name):
    print("hi "+name+"'s world.")
my_func('tyl23r')

hi tyl23r's world.


In [333]:
# function with a return and multi line comment ie; docstring
def plus_five(num):
    """
    adds five to a number
    """
    return num+5

output = plus_five(5000)
print(output)

5005


In [334]:
# shift + plus shows comments above 
plus_five

<function __main__.plus_five(num)>

In [335]:
def times2(var):
    """
    multiplies var by 2
    """
    return var*2
seqtwo = [1,2,3,4,5]
print(seqtwo)

[1, 2, 3, 4, 5]


In [336]:
print(times2(2))

4


In [337]:
print(map(times2, seqtwo))
list(map(times2, seqtwo))

[2, 4, 6, 8, 10]

In [338]:
[map(times2, seqtwo)]

In [339]:
## Lambda expressions

In [340]:
t = lambda var:var*2

In [341]:
t(6)

12

In [342]:
seq_o = [3,4,5]
(map(lambda num: num*3,seq_o))

In [343]:
list(map(lambda num: num*3,seq_o))

[9, 12, 15]

## Filter
a filter must return a boolean value (true or false)

In [344]:
seq_v = [-2,2,3,4,5]
list(filter(lambda num: num%2 == 0,seq_v))

[-2, 2, 4]

In [345]:
## Method

In [346]:
s = 'hello my name is teelur'
s.capitalize()

'Hello my name is teelur'

In [347]:
# use parthensis to 'execute'
s.lower()

'hello my name is teelur'

In [348]:
s.lower

<function str.lower()>

In [349]:
s.upper()

'HELLO MY NAME IS TEELUR'

In [350]:
# by default the split function splits on white spaces
# helpful for text analysis later in notes
s.split()

['hello', 'my', 'name', 'is', 'teelur']

In [351]:
tweet = 'Yay sports, #sports are cool'
tweet.split()

['Yay', 'sports,', '#sports', 'are', 'cool']

In [352]:
hashtag_tweet = tweet.split('#')[1]
print(hashtag_tweet)

sports are cool


In [353]:
hashtag_tweet.split()

['sports', 'are', 'cool']

In [354]:
dictionary_tool = {'k1':1,'k2':2}
print(dictionary_tool)

{'k1': 1, 'k2': 2}


In [355]:
dictionary_tool.items()

dict_items([('k1', 1), ('k2', 2)])

In [356]:
dictionary_tool.keys()

dict_keys(['k1', 'k2'])

In [357]:
# The pop() method removes the element at the specified position.
# you can pass a pop to another variable
# pop can be used to remove an element and return that element to a variable
dictionary_tool.pop('k2')
# print to see element is not available in the dictionary
print(dictionary_tool)

{'k1': 1}


In [358]:
dictionary_tool.values()

dict_values([1])

## NumPy Arrays

In [359]:
our_list = [1,2,3]
import numpy as np

In [360]:
np.array(our_list)

array([1, 2, 3])

In [361]:
arr = np.array(our_list)

In [362]:
arr

array([1, 2, 3])

In [363]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [364]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [365]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [366]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [367]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [368]:
# calling index 1
np.arange(0,10)[1]

1

In [369]:
# trimming from left side
np.arange(0,11)[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [370]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [371]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [372]:
np.zeros(3)

array([0., 0., 0.])

In [373]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [374]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [375]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [376]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [377]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [378]:
np.random.rand(5)

array([0.25545484, 0.53160969, 0.2373813 , 0.91858986, 0.45432259])

In [379]:
arr = np.random.rand(5,5)
print(arr)

[[0.71743113 0.65817726 0.19108393 0.50708401 0.32256332]
 [0.77701835 0.71136388 0.08702039 0.24536062 0.49208711]
 [0.97280393 0.70860624 0.7689119  0.36248891 0.47468029]
 [0.13509401 0.31404985 0.10947644 0.25380936 0.7343682 ]
 [0.79540098 0.33979052 0.50639789 0.36214218 0.13464385]]


In [380]:
np.random.randint(1,100,10)

array([75, 65, 64, 71, 45, 20, 55,  1, 91, 47])

In [381]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [382]:
ranarr = np.random.randint(0,200,10)

In [383]:
print(ranarr)
ranarr[0:-1]

[103  94 127 170  50 191 127  96   5  53]


array([103,  94, 127, 170,  50, 191, 127,  96,   5])

In [384]:
# number of rows * number of columns must be the same as np.arange above
arr.reshape(5,5)

array([[0.71743113, 0.65817726, 0.19108393, 0.50708401, 0.32256332],
       [0.77701835, 0.71136388, 0.08702039, 0.24536062, 0.49208711],
       [0.97280393, 0.70860624, 0.7689119 , 0.36248891, 0.47468029],
       [0.13509401, 0.31404985, 0.10947644, 0.25380936, 0.7343682 ],
       [0.79540098, 0.33979052, 0.50639789, 0.36214218, 0.13464385]])

In [385]:
ranarr.max()
ranarr.argmax()


5

In [386]:
ranarr.min()
ranarr.argmin()


8

In [387]:
ranarr.sum()


1016

In [388]:
ranarr.shape

(10,)

In [389]:
arr.shape

(5, 5)

In [390]:
arr.reshape(25,)

array([0.71743113, 0.65817726, 0.19108393, 0.50708401, 0.32256332,
       0.77701835, 0.71136388, 0.08702039, 0.24536062, 0.49208711,
       0.97280393, 0.70860624, 0.7689119 , 0.36248891, 0.47468029,
       0.13509401, 0.31404985, 0.10947644, 0.25380936, 0.7343682 ,
       0.79540098, 0.33979052, 0.50639789, 0.36214218, 0.13464385])

In [391]:
arr.reshape(5,5)

array([[0.71743113, 0.65817726, 0.19108393, 0.50708401, 0.32256332],
       [0.77701835, 0.71136388, 0.08702039, 0.24536062, 0.49208711],
       [0.97280393, 0.70860624, 0.7689119 , 0.36248891, 0.47468029],
       [0.13509401, 0.31404985, 0.10947644, 0.25380936, 0.7343682 ],
       [0.79540098, 0.33979052, 0.50639789, 0.36214218, 0.13464385]])

In [392]:
arr.dtype

dtype('float64')

In [393]:
from numpy.random import randint

In [394]:
randint(2,20)

11

In [395]:
## NumpPy Indexing and Selection

In [396]:
import numpy as np

In [397]:
# create array in numpy using arange()
arr = np.arange(0,11)

In [398]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [399]:
# get value at index2
arr[2]

2

In [400]:
arr[:2]

array([0, 1])

In [401]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [402]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [403]:
arr[-2:]

array([ 9, 10])

In [404]:
# numpy array is different in this realm as it allows you to broadcast..
arr[0:5] = '0'
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [405]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [406]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [407]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [408]:
# slice of arr above shows a "view" of the original array
# and changes the original array 
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [409]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [410]:
# changes we do without .copy() make changes to the original array
# because arr_copy above is a .copy() we won't see 100's repeated below
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## NumPy Indexing and Selection

In [411]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [412]:
# double bracket format
# index starts at 'zero'
arr_2d[0][0]

5

In [413]:
arr_2d[1][1]

25

In [414]:
arr_2d[0]

array([ 5, 10, 15])

In [415]:
arr_2d[2][1]

40

In [416]:
# slice notation along with single brackets comma indexing notation
# with numpy to grab subsections of the array
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [417]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [418]:
arr_2d[:,-1:]

array([[15],
       [30],
       [45]])

In [419]:
arr_2d[:,:1]

array([[ 5],
       [20],
       [35]])

In [420]:
arr_2d[:1,:]

array([[ 5, 10, 15]])

In [421]:
arr_2d[-1:,:]

array([[35, 40, 45]])

In [422]:
narr = np.arange(1,11)

In [423]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [424]:
bool_arr = narr > 5

In [425]:
# Use boolean array to conditional select elements based on the condition
# it only returns instances based on it being TRUE
narr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [426]:
# better to do it all in one step
# pass conditional statement in the []
# syntax notation, conditional selection
narr[narr>5]

array([ 6,  7,  8,  9, 10])

In [427]:
# conditional statement passes a boolean array of true and selects elements where true
narr[narr<9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [428]:
narr[narr<3]

array([1, 2])