In [1]:
# comments

## Numbers
Using numbers in python and math.

In [2]:
# int
1

1

In [3]:
# float
1.0

1.0

In [4]:
# addition
1+1

2

In [5]:
# multiplication
1*3

3

In [6]:
# python 2 division
1/2.0
# python 3
1/2

0.5

In [7]:
# two to the power of 4
2 ** 4

16

In [8]:
# mod function
# if zero then even number
4 % 2

0

In [9]:
# remainder left over is 1
5 % 2

1

In [10]:
5 / 2

2.5

## Variables
Using variables in python.

In [11]:
# without () ouputs like normal math
xx = 4 + 2 * 3 + 6
print (xx)
# with () ouputs like normal math
yy = (4 + 2) * (3 + 6)
print (yy)

16
54


In [12]:
var = 2

In [13]:
# you can output in jupyter like
var

2

In [14]:
# however, print() is the common practice
print(var)

2


In [15]:
x = 2
y = 3

In [16]:
x+y

5

In [17]:
x = x+x

In [18]:
x

4

In [19]:
x = x+x

In [20]:
x

8

In [21]:
# variables can not start with numbers
111var = 5

SyntaxError: invalid syntax (<ipython-input-21-82b7c26456e4>, line 2)

In [ ]:
# proper variables use "snake_case"
the_variable_name = 5

## Strings
Strings in python work like...

In [ ]:
# string with '' quotes
'single quotes'

In [ ]:
# string with "" quotes
"double quotes"

In [ ]:
# string with a single ' and "" wrapping
"double's quote"

In [ ]:
# string with a single " and '' wrapping
'single"s quote'

## Using variables with strings
Strings/numbers and their usage with variables.

In [ ]:
# printing
to_print = "hi wrold"

In [ ]:
# works in jupyter
to_print

In [ ]:
# common practice
print(to_print)

In [ ]:
# using variable names in format()
num = 15
name = 'Tyler'
title = 'The Beast'
# format(order,you,want,variables_to_pass_in_brace_brackets)
print('My fave # is {} and my name is {}, {}'.format(num,name,title))
# here we can re-use without worrying about order
print('My fave # is {one} and my name is {two}, {three} named {two}-zilla-g'.format(one=num,two=name,three=title))

In [ ]:
s='hello'

In [ ]:
# indexing starts at zero
# counting in python starts with zero, then one, two, etc.
s[0]

In [ ]:
# grabbing "o" from hello.
s[4]

In [ ]:
# how it's done using numbers, in a list, a little similar
g=[0,1,2,3]

In [ ]:
g[2]

## Trimming a string.
Trimming strings in python and examples.

In [ ]:
# r is a sequence of elements
r='asfghjkl'
# [number:number] lets you grab a sequence of elements
# column notation, aka 'slice syntax'
# trim 1 letter from the left
r[1:]

In [ ]:
# trim 3 letter from the right
r[:3]

In [ ]:
# adding negative reverses the trim direction
# example; trim 3 letter from the left
r[:-3]

In [ ]:
# trim 3 letter from the left
r[3:]

In [ ]:
# adding negative reverses the trim starting direction
# example; trim 3 letter from the left
r[-3:]

In [ ]:
r[2:5]

## Lists
Using a list in python with examples.

In [ ]:
# lists numbers
[1,2,3]

In [ ]:
# lists strings
['a','b','c']

In [ ]:
# variable with string list
a_cool_list = ['a','b','c']
# appending 'meow'
a_cool_list.append('meow')
print (a_cool_list)
# removing 'meow'
a_cool_list.remove('meow')
print (a_cool_list)

In [ ]:
# appending 'd'
a_cool_list.append('d')
# print to check change
print (a_cool_list)
a_cool_list.append('e')
# print to check change
print (a_cool_list)
a_cool_list.append('f')
# print to check change
print (a_cool_list)

In [ ]:
# trim both sides of the list
a_cool_list[2:5]

In [ ]:
# change the value in the list based on index #\
a_cool_list[0] = 'Meow'
a_cool_list

## Tuples vs lists vs sets
Tuples can't be changed, lists can be changed. Use tuple when user can't change what's inside of object.

In [ ]:
# tuple ()
t = ('new','car','vroom')
# list []
l = ['new','car','vroom']

# attempting to change first value in tuple
# tuples can not be changed, will fail, see error
# items in tuple can not be mutated
t[0] = 'fast'

In [ ]:
# change first value to 'fast'
# lists can be changed
l[0] = 'fast'
# print list to see change
print(l)

In [ ]:
# sets [], a set only passes unique elements when printed
# sets are a collection of unique elements
# vroom 2 will be removed in s
s = {'new','car','vroom','vroom'} 
# print to see vroom removed
print(s)

In [ ]:
# adding 5 to set
s.add(5)
print(s)

In [ ]:
# convert list to set with set()
convert = set([1,1,1,1,1,12,2,3,4,5,5,5,5,5,55,33])
# print to see unique elements.
print(convert)

##  Dictonary
A dictonary in python. Dictonary do not retain an order, they are key value paired mappings. 

In [ ]:
d = {'key1':'value','key2':123}
d['key2']

In [ ]:
d['key1']

In [ ]:
d={'k1':[1,2,3]}

In [ ]:
d

In [ ]:
d['k1']

In [ ]:
print(d['k1'][1])
a_list = d['k1']

In [ ]:
a_list[1]

## Comparison operators
Comparison operators allow you to compare two elements to each other, and booleans.

In [ ]:
1 > 3

In [ ]:
1 < 3

In [ ]:
1 >= 3

In [ ]:
1 <= 3

In [ ]:
1 == 3

In [ ]:
1 = 1

In [ ]:
1 != 3

In [ ]:
'hi' != 'bye'

In [ ]:
1 < 2 and 2 < 3

In [ ]:
1 < 2 and 2 > 3

In [ ]:
# more readable
(1 < 2) or (2 < 1)

In [ ]:
# more readable
(1 < 2) and (2 < 1)

In [ ]:
True and True

In [ ]:
False or True

## If statement
If then else...

In [ ]:
if 1<2:
    print('woot!')

In [ ]:
if True:
    print('output code')

In [ ]:
# needs to be uppercase first letter
if true:
    print('output code')

In [ ]:
if 1 == 2:
    print ('tyker')
else:
    print ('garr3ttt')

In [ ]:
# python only executes the first true statement, and that's all.
if 1 == 2:
    print ('tyker')
elif 'meow' == 'meow':
    print ('m3ow')
elif 3 == 3:
    print ('alexand3r')
else:
    print ('garr3ttt')

## for loop

In [ ]:
seq = [1,2,3,4,5,6,7,8,9]

In [ ]:
for i in seq:
    print(i)

In [ ]:
for number in seq:
    print(number)

In [ ]:
# while loops
# execute a loop, as long as the condition is true.
i = 1
# i < 10 is the condition that needs to be true for the loop to run
while i < 10:
    # printing each loop the following
    print ('You gained ${a}.00 USD'.format(a=i))
    # increases +1 per loop, until it reaches 10<10 which is not true
    i = i+1

In [ ]:
i = 1
c = 10
while i < c:
    print ('You gained ${}.00 USD, out of ${}.00 total'.format(i, c))
    i = i+1

## For loop and Range

In [ ]:
m = [1,2,3,4,5,5]
for x in m:
    print(x)

In [ ]:
# using a list generator, range()
for x in range(0,5):
    print(x)

In [ ]:
# using a list generator, range()
for x in list(range(0,5)):
    print(x)

In [ ]:
list(range(0,6))

In [ ]:
list(range(10))

In [ ]:
list(range(1,11))

## List comprehension
List comprehension - save writing when you're creating a for loop to create a list

In [ ]:
# for loop can be used, however list comprehension below is 1 line
# a list of numbers (num)
h = [1,2,3,4]
# defining a list "out"
out = []

for num in h:
    out.append(num**2)

print(out)

In [ ]:
io = [num**2 for num in h]
print(io)

In [ ]:
[num**2 for num in h]

## Functions
A function in python helps you write less code.

In [ ]:
def my_function(param1):
    print(param1)

In [ ]:
my_function('hey world')

In [ ]:
def my_func(name):
    print("hi "+name+"'s world.")
my_func('tyl23r')

In [ ]:
# function with a return and multi line comment ie; docstring
def plus_five(num):
    """
    adds five to a number
    """
    return num+5

output = plus_five(5000)
print(output)

In [ ]:
# shift + plus shows comments above 
plus_five

In [23]:
def times2(var):
    """
    multiplies var by 2
    """
    return var*2
seqtwo = [1,2,3,4,5]
print(seqtwo)

[1, 2, 3, 4, 5]


In [ ]:
print(times2(2))

In [24]:
print(map(times2, seqtwo))
list(map(times2, seqtwo))

[2, 4, 6, 8, 10]

In [25]:
[map(times2, seqtwo)]

In [ ]:
## Lambda expressions

In [26]:
t = lambda var:var*2

In [27]:
t(6)

12

In [28]:
seq_o = [3,4,5]
(map(lambda num: num*3,seq_o))

In [29]:
list(map(lambda num: num*3,seq_o))

[9, 12, 15]

## Filter
a filter must return a boolean value (true or false)

In [33]:
seq_v = [-2,2,3,4,5]
list(filter(lambda num: num%2 == 0,seq_v))

[-2, 2, 4]

In [34]:
## Method

In [35]:
s = 'hello my name is teelur'
s.capitalize()

'Hello my name is teelur'

In [36]:
# use parthensis to 'execute'
s.lower()

'hello my name is teelur'

In [37]:
s.lower

<function str.lower()>

In [38]:
s.upper()

'HELLO MY NAME IS TEELUR'

In [39]:
# by default the split function splits on white spaces
# helpful for text analysis later in notes
s.split()

['hello', 'my', 'name', 'is', 'teelur']

In [40]:
tweet = 'Yay sports, #sports are cool'
tweet.split()

['Yay', 'sports,', '#sports', 'are', 'cool']

In [44]:
hashtag_tweet = tweet.split('#')[1]
print(hashtag_tweet)

sports are cool


In [45]:
hashtag_tweet.split()

['sports', 'are', 'cool']

In [55]:
dictionary_tool = {'k1':1,'k2':2}
print(dictionary_tool)

{'k1': 1, 'k2': 2}


In [48]:
dictionary_tool.items()

dict_items([('k1', 1), ('k2', 2)])

In [57]:
dictionary_tool.keys()

dict_keys(['k1'])

In [ ]:
# The pop() method removes the element at the specified position.
# you can pass a pop to another variable
# pop can be used to remove an element and return that element to a variable
dictionary_tool.pop('k2')
# print to see element is not available in the dictionary
print(dictionary_tool)

In [58]:
dictionary_tool.values()

dict_values([1])

## NumPy Arrays

In [59]:
our_list = [1,2,3]
import numpy as np

In [60]:
np.array(our_list)

array([1, 2, 3])

In [61]:
arr = np.array(our_list)

In [62]:
arr

array([1, 2, 3])

In [63]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [64]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [66]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# calling index 1
np.arange(0,10)[1]

1

In [77]:
# trimming from left side
np.arange(0,11)[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [80]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [81]:
np.zeros(3)

array([0., 0., 0.])

In [83]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [150]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [93]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
np.random.rand(5)

array([0.39555763, 0.19030175, 0.04008595, 0.96229853, 0.58049051])

In [136]:
arr = np.random.rand(5,5)
print(arr)

[[0.84287781 0.51847205 0.82898494 0.62560558 0.53235199]
 [0.76667026 0.41885981 0.99337379 0.22159391 0.13669792]
 [0.97067446 0.30492538 0.12149933 0.69581807 0.89746003]
 [0.04299687 0.44875492 0.16693166 0.03720444 0.64588208]
 [0.67203191 0.88509929 0.07555104 0.02733259 0.78219305]]


In [100]:
np.random.randint(1,100,10)

array([94, 36, 73, 21, 51, 70, 25, 19, 90, 77])

In [141]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [158]:
ranarr = np.random.randint(0,200,10)

In [159]:
print(ranarr)
ranarr[0:-1]

[ 79 160  16 174  31 191  92  88  68 158]


array([ 79, 160,  16, 174,  31, 191,  92,  88,  68])

In [143]:
# number of rows * number of columns must be the same as np.arange above
arr.reshape(5,5)

array([[0.84287781, 0.51847205, 0.82898494, 0.62560558, 0.53235199],
       [0.76667026, 0.41885981, 0.99337379, 0.22159391, 0.13669792],
       [0.97067446, 0.30492538, 0.12149933, 0.69581807, 0.89746003],
       [0.04299687, 0.44875492, 0.16693166, 0.03720444, 0.64588208],
       [0.67203191, 0.88509929, 0.07555104, 0.02733259, 0.78219305]])

In [163]:
ranarr.max()
ranarr.argmax()


5

In [161]:
ranarr.min()
ranarr.argmin()


2

In [162]:
ranarr.sum()


1057

In [164]:
ranarr.shape

(10,)

In [165]:
arr.shape

(5, 5)

In [166]:
arr.reshape(25,)

array([0.84287781, 0.51847205, 0.82898494, 0.62560558, 0.53235199,
       0.76667026, 0.41885981, 0.99337379, 0.22159391, 0.13669792,
       0.97067446, 0.30492538, 0.12149933, 0.69581807, 0.89746003,
       0.04299687, 0.44875492, 0.16693166, 0.03720444, 0.64588208,
       0.67203191, 0.88509929, 0.07555104, 0.02733259, 0.78219305])

In [167]:
arr.reshape(5,5)

array([[0.84287781, 0.51847205, 0.82898494, 0.62560558, 0.53235199],
       [0.76667026, 0.41885981, 0.99337379, 0.22159391, 0.13669792],
       [0.97067446, 0.30492538, 0.12149933, 0.69581807, 0.89746003],
       [0.04299687, 0.44875492, 0.16693166, 0.03720444, 0.64588208],
       [0.67203191, 0.88509929, 0.07555104, 0.02733259, 0.78219305]])

In [168]:
arr.dtype

dtype('float64')

In [169]:
from numpy.random import randint

In [170]:
randint(2,20)

16

In [171]:
## NumpPy Indexing and Selection

In [172]:
import numpy as np

In [175]:
# create array in numpy using arange()
arr = np.arange(0,11)

In [176]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
# get value at index2
arr[2]

2

In [178]:
arr[:2]

array([0, 1])

In [179]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [180]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [181]:
arr[-2:]

array([ 9, 10])

In [190]:
# numpy array is different in this realm as it allows you to broadcast..
arr[0:5] = '0'
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [192]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [193]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [195]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [196]:
# slice of arr above shows a "view" of the original array
# and changes the original array 
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [199]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [200]:
# changes we do without .copy() make changes to the original array
# because arr_copy above is a .copy() we won't see 100's repeated below
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## NumPy Indexing and Selection

In [201]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [202]:
# double bracket format
# index starts at 'zero'
arr_2d[0][0]

5

In [204]:
arr_2d[1][1]

25

In [207]:
arr_2d[0]

array([ 5, 10, 15])

In [208]:
arr_2d[2][1]

40

In [209]:
# slice notation along with single brackets comma indexing notation
# with numpy to grab subsections of the array
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [210]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [228]:
arr_2d[:,-1:]

array([[15],
       [30],
       [45]])

In [229]:
arr_2d[:,:1]

array([[ 5],
       [20],
       [35]])

In [230]:
arr_2d[:1,:]

array([[ 5, 10, 15]])

In [234]:
arr_2d[-1:,:]

array([[35, 40, 45]])

In [235]:
narr = np.arange(1,11)

In [236]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [239]:
bool_arr = narr > 5

In [244]:
# Use boolean array to conditional select elements based on the condition
# it only returns instances based on it being TRUE
narr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [245]:
# better to do it all in one step
# pass conditional statement in the []
# syntax notation, conditional selection
narr[narr>5]

array([ 6,  7,  8,  9, 10])

In [246]:
# conditional statement passes a boolean array of true and selects elements where true
narr[narr<9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [247]:
narr[narr<3]

array([1, 2])